### ISSUE TITLE
Tooltips on images

### ISSUE THREAD

**Issue by xkomczax** [Fannon/SimpleTooltip#1]
Hi,

is there an option for making tooltips on images? If not, are you planning to implement it? 

Thanks for answer
xkomczax

**Comment by Fannon** [comment]
Hello xkomczax,

it would be easy to add support for simple images, which would work like the info-icon tooltip. If you want full MediaWiki image syntax support I guess this would be more difficult.

What's your use-case?

Best, 
Simon

**Comment by xkomczax** [comment]
Hi Simon,

as of me, simple image tooltip will be more than enough! :-)

Best,
xkomczax

**Comment by Fannon** [comment]
Great, that should not be difficult ;) 
I'll look into it the next days and keep you updated!

**Comment by xkomczax** [comment]
Thanks for such a quick answer. I will keep my eye on this repository for next few days ;-)

**Comment by Fannon** [comment]
Should be implemented now, please tell me if it works like expected!

https://www.mediawiki.org/w/index.php?title=Extension:SimpleTooltip#Inline-Image_tooltip:

642bd38e92dde73c8d44c64259107ed8d9e010d8

**Comment by xkomczax** [comment]
Yeah, just uploaded new version and works like a charm! :-)

Thanks a lot! :-)
