### ISSUE TITLE
Making a release?

### ISSUE THREAD

**Issue by kghbln** [Fannon/SimpleTooltip#4]
What about tagging master and make the 0.1 release?

**Comment by Fannon** [comment]
Good idea :)
I'll probably review and tag all my MediaWiki extensions the next weeks.

**Comment by kghbln** [comment]
I guess this is a tiny extra that will increase trust in this extension. So ... :)

**Comment by Fannon** [comment]
Yes, you're absolutely right about that! The extension should be quite stable anyhow.

**Comment by kghbln** [comment]
Just added more fluff to the extension's page on mw.o Hope you like this. Still it's a wiki ... I see great potential for this one.

**Comment by Fannon** [comment]
Thanks alot, Karsten! :)

**Comment by kghbln** [comment]
Well I have to thank you for this cool extension!
