### ISSUE TITLE
SimpleTooltip does't work with MediaWiki 1.25 yet

### ISSUE THREAD

**Issue by jaideraf** [Fannon/SimpleTooltip#6]
Hi, I tested the SimpleTooltip extension on a MW 1.25wmf22 and it didn't work.

**Comment by Fannon** [comment]
Hello Jaideraf,

what exactly didn't work? Do you have any error messages?

Best, Simon

**Comment by Fannon** [comment]
I've just updated to MW 1.25.1 myself, and SimpleTooltip is still working.

**Comment by jaideraf** [comment]
Oh, sorry, you are right.
I updated to MW 1.25.1, now it works great. Thank you.
Maybe the problem arose because I didn't upgrade the Vector skin in the first time, I don't know...
I am not a developer, just a user.
Again, so sorry, my fault.

Best, Jaider.
